In [8]:
from pathlib import Path
import pandas as pd

In [15]:
p = Path.cwd()
repo_root = None
while True:
    if (p / "data").exists() and (p / "notebooks").exists():
        repo_root = p
        break
    if p == p.parent:
        raise FileNotFoundError("Could not find project root containing 'data' and 'notebooks'")
    p = p.parent
data_path = repo_root / "data" / "raw" / "sub-01" / "emg"

In [16]:
channels_df = pd.read_csv(f"{data_path}/sub-01_task-Cyl_acq-cometa_channels.tsv", sep="\t")

In [17]:
channels_df

         name type units  sampling_frequency
0    Lat_Tric  EMG    mV                2000
1    Med_Tric  EMG    mV                2000
2    Long_Bic  EMG    mV                2000
3   Short_Bic  EMG    mV                2000
4    Ant_Delt  EMG    mV                2000
5   Midd_Delt  EMG    mV                2000
6   Post_Delt  EMG    mV                2000
7  Upper_Trap  EMG    mV                2000
8  Brachiorad  EMG    mV                2000
9  W_pronator  EMG    mV                2000

In [18]:
channels = channels_df['name'].values
list(channels)

['Lat_Tric',
 'Med_Tric',
 'Long_Bic',
 'Short_Bic',
 'Ant_Delt',
 'Midd_Delt',
 'Post_Delt',
 'Upper_Trap',
 'Brachiorad',
 'W_pronator']

In [19]:
emg_df = pd.read_csv(f"{data_path}/sub-01_task-Cyl_acq-cometa_emg.csv", index_col=0, names=channels)

In [20]:
emg_df

,Lat_Tric,Med_Tric,Long_Bic,Short_Bic,Ant_Delt,Midd_Delt,Post_Delt,Upper_Trap,Brachiorad,W_pronator
0.0000,-0.002773,0.002853,0.006152,-0.002288,-0.112803,-0.012824,0.004329,-0.060026,0.018706,-0.006721
0.0005,-0.003093,0.005602,0.005929,-0.000833,-0.076491,-0.012279,0.006786,-0.046519,0.015929,-0.004824
0.0010,-0.007311,0.004870,0.004827,0.000931,-0.049687,-0.011865,0.007768,-0.030972,0.014491,-0.000269
0.0015,-0.013020,0.000958,0.002204,0.000846,-0.036271,-0.011504,0.005193,-0.017412,0.018863,0.001705
0.0020,-0.014849,-0.001548,0.000461,-0.000489,-0.026264,-0.011060,0.000721,-0.005992,0.024204,-0.001793
...,...,...,...,...,...,...,...,...,...,...
59.3480,0.001090,-0.001065,-0.001347,0.001346,-0.070725,-0.052964,-0.003011,-0.018248,0.011570,-0.004263
59.3485,-0.004828,-0.003581,-0.000431,-0.000071,-0.084840,-0.033415,-0.002607,-0.025896,0.011220,-0.015092
59.3490,-0.007484,-0.003211,0.000032,0.002496,-0.077380,-0.022940,0.000027,-0.031151,0.008106,-0.027704
59.3495,-0.009176,-0.000145,-0.000740,0.004173,-0.070176,-0.020611,0.003481,-0.032954,0.006043,-0.038457
59.3500,-0.014340,0.001821,-0.002360,0.003260,-0.070610,-0.018105,0.005193,-0.030417,0.010102,-0.040072